# Analisis con Pandas y Kaggle

**Preparacion del entorno**
Primero debemos preparar el entorno de trabajo con Pandas

**Cargar los datos**
Una vez seleccionado y descargado el dataset de Kaggle se realiza la carga del archivo csv en un DataFrame de Pandas

In [ ]:
import pandas as pd

df = pd.read_csv("/Users/carlis/mi_proyecto/Pandas y Visualizacion/supermarket_sales 2.csv")

**Exploracion inicial de los datos**
En esta parte comenzamos a revisar y explorar la informacion del DataFrame utilizando las operaciones basicas como Head, Tail, Info, Describe y Types.

Con Head y Tail podemos visualizar las primeras y ultimas filas respectivamente
Con Info entrega un resumen conciso del DataFrame
Con Describe "genera estadisticas descriptivas que resumen la tendencia central, dispersion y forma de la distribucion de un conjunto de datos"
Con Types nos permite saber los tipos de datos de cada columna

In [5]:
print("Primeras filas del DataFrame:")
print(df.head(10))

print("Ultimas filas del DataFrame:")
print(df.tail(5))

print("Informacion del DataFrame:")
print(df.info())

print("Estadisticas descriptivas del DataFrame:")
print(df.describe().round(2))

print("Tipos originales:")
print(df.dtypes)

Primeras filas del DataFrame:
    Invoice ID Branch       City Customer type  Gender  \
0  750-67-8428      A     Yangon        Member  Female
1  226-31-3081      C  Naypyitaw        Normal  Female
2  631-41-3108      A     Yangon        Normal    Male
3  123-19-1176      A     Yangon        Member    Male
4  373-73-7910      A     Yangon        Normal    Male
5  699-14-3026      C  Naypyitaw        Normal    Male
6  355-53-5943      A     Yangon        Member  Female
7  315-22-5665      C  Naypyitaw        Normal  Female
8  665-32-9167      A     Yangon        Member  Female
9  692-92-5582      B   Mandalay        Member  Female

             Product line  Unit price  Quantity   Tax 5%     Total       Date  \
0       Health and beauty       74.69         7  26.1415  548.9715   1/5/2019
1  Electronic accessories       15.28         5   3.8200   80.2200   3/8/2019
2      Home and lifestyle       46.33         7  16.2155  340.5255   3/3/2019
3       Health and beauty       58.22         8  23.2880  489.0480  1/27/2019
4       Sports and travel       86.31         7  30.2085  634.3785   2/8/2019
5  Electronic accessories       85.39         7  29.8865  627.6165  3/25/2019
6  Electronic accessories       68.84         6  20.6520  433.6920  2/25/2019
7      Home and lifestyle       73.56        10  36.7800  772.3800  2/24/2019
8       Health and beauty       36.26         2   3.6260   76.1460  1/10/2019
9      Food and beverages       54.84         3   8.2260  172.7460  2/20/2019

    Time      Payment    cogs  gross margin percentage  gross income  Rating
0  13:08      Ewallet  522.83                 4.761905       26.1415     9.1
1  10:29         Cash   76.40                 4.761905        3.8200     9.6
2  13:23  Credit card  324.31                 4.761905       16.2155     7.4
3  20:33      Ewallet  465.76                 4.761905       23.2880     8.4
4  10:37      Ewallet  604.17                 4.761905       30.2085     5.3
5  18:30      Ewallet  597.73                 4.761905       29.8865     4.1
6  14:36      Ewallet  413.04                 4.761905       20.6520     5.8
7  11:38      Ewallet  735.60                 4.761905       36.7800     8.0
8  17:15  Credit card   72.52                 4.761905        3.6260     7.2
9  13:27  Credit card  164.52                 4.761905        8.2260     5.9
Ultimas filas del DataFrame:
      Invoice ID Branch       City Customer type  Gender         Product line  \
995  233-67-5758      C  Naypyitaw        Normal    Male    Health and beauty
996  303-96-2227      B   Mandalay        Normal  Female   Home and lifestyle
997  727-02-1313      A     Yangon        Member    Male   Food and beverages
998  347-56-2442      A     Yangon        Normal    Male   Home and lifestyle
999  849-09-3807      A     Yangon        Member  Female  Fashion accessories

     Unit price  Quantity   Tax 5%      Total       Date   Time  Payment  \
995       40.35         1   2.0175    42.3675  1/29/2019  13:46  Ewallet
996       97.38        10  48.6900  1022.4900   3/2/2019  17:16  Ewallet
997       31.84         1   1.5920    33.4320   2/9/2019  13:22     Cash
998       65.82         1   3.2910    69.1110  2/22/2019  15:33     Cash
999       88.34         7  30.9190   649.2990  2/18/2019  13:28     Cash

       cogs  gross margin percentage  gross income  Rating
995   40.35                 4.761905        2.0175     6.2
996  973.80                 4.761905       48.6900     4.4
997   31.84                 4.761905        1.5920     7.7
998   65.82                 4.761905        3.2910     4.1
999  618.38                 4.761905       30.9190     6.6
Informacion del DataFrame:
<class 'pandas.DataFrame'>
RangeIndex: 1000 entries, 0 to 999
Data columns (total 17 columns):
 #   Column                   Non-Null Count  Dtype
---  ------                   --------------  -----
 0   Invoice ID               1000 non-null   str
 1   Branch                   1000 non-null   str
 2   City                     1000 non-null   str
 3   Customer type            1000 non-null   str
 4   Gender                   1000 non-null   str
 5   Product line             1000 non-null   str
 6   Unit price               1000 non-null   float64
 7   Quantity                 1000 non-null   int64
 8   Tax 5%                   1000 non-null   float64
 9   Total                    1000 non-null   float64
 10  Date                     1000 non-null   str
 11  Time                     1000 non-null   str
 12  Payment                  1000 non-null   str
 13  cogs                     1000 non-null   float64
 14  gross margin percentage  1000 non-null   float64
 15  gross income             1000 non-null   float64
 16  Rating                   1000 non-null   float64
dtypes: float64(7), int64(1), str(9)
memory usage: 132.9 KB
None
Estadisticas descriptivas del DataFrame:
       Unit price  Quantity   Tax 5%    Total     cogs  \
count     1000.00   1000.00  1000.00  1000.00  1000.00
mean        55.67      5.51    15.38   322.97   307.59
std         26.49      2.92    11.71   245.89   234.18
min         10.08      1.00     0.51    10.68    10.17
25%         32.88      3.00     5.92   124.42   118.50
50%         55.23      5.00    12.09   253.85   241.76
75%         77.94      8.00    22.45   471.35   448.90
max         99.96     10.00    49.65  1042.65   993.00

       gross margin percentage  gross income   Rating
count                  1000.00       1000.00  1000.00
mean                      4.76         15.38     6.97
std                       0.00         11.71     1.72
min                       4.76          0.51     4.00
25%                       4.76          5.92     5.50
50%                       4.76         12.09     7.00
75%                       4.76         22.45     8.50
max                       4.76         49.65    10.00
Tipos originales:
Invoice ID                     str
Branch                         str
City                           str
Customer type                  str
Gender                         str
Product line                   str
Unit price                 float64
Quantity                     int64
Tax 5%                     float64
Total                      float64
Date                           str
Time                           str
Payment                        str
cogs                       float64
gross margin percentage    float64
gross income               float64
Rating                     float64
dtype: object

**Limpieza de datos**
En este punto revisamos los tipos de datos de cada columna, si tenemos datos nulos y/o duplicados

Para el DataFrame seleccionado revisamos lo siguiente:
Primero se confirma si tenemos datos nulos y logramos verificar que este archivo no contiene datos nulos
Segundo, se revisa el tipo de datos de la columnas y nos encontramos con que tenemos la columna Date con un tipo de dato str y consideramos que para un mejor analisis esta informacion debe esta en tipo datetime ya que asi podriamos tomar esta columna y obtener informacion de las ventas segun el mes o año. Ademas se revisa que la columna Quantity se encuentra en tipo float (decimales) y se realiza el cambio a tipo int (numero entero)
Tercero, se realiza la revision para verificar si tenemos filas duplicadas, para este caso nos indica que no hay filas duplicadas, luego se decide revisar si la columna Payment tiene informacion duplicada y nos indica que existen duplicados lo que es correcto ya que en esta columna podemos confirmar como realizo el pago cada cliente, ya sea efectivo, tarjeta y otros.

In [7]:
print("Verificacion de datos nulos:")
print(df.isnull().sum())

print("Cantidad de nulos en la columna Date:")
print(df['Date'].isnull().sum())


#en este caso se visualiza que la fecha esta en formato str segun lo revisdo en la red esto estaria bien al venir de un archivo csv pero para analizar datos por este medio ese formato no seria de ayuda por lo tanto se realiza este cambio
df['Date'] = pd.to_datetime(df['Date'], format="%m/%d/%Y")
print("Fecha convertida:")
print(df[['Date']].dtypes)

#Otro caso que nos interesa corregir sera la columna Quantity ya que se encuentra en float osea numero decimal y consideramos que para un mejor analisis es necesario que se cambie a numero entero
df['Quantity'] = df['Quantity'].astype(int)
print("Cantidad convertida:")
print(df[['Quantity']].dtypes)

#Confirmar si existen filas duplicadas
n_duplicados = df.duplicated().sum()
print(f"Filas duplicadas: {n_duplicados}")

col_duplicados = df.duplicated(subset=['Payment']).sum()
print(f"Columna payment duplicada: {col_duplicados}")
# para este caso se entiende que este bien que existan datos duplicados en la columna payment ya que esta columna indica el metodo de pago

Verificacion de datos nulos:
Invoice ID                 0
Branch                     0
City                       0
Customer type              0
Gender                     0
Product line               0
Unit price                 0
Quantity                   0
Tax 5%                     0
Total                      0
Date                       0
Time                       0
Payment                    0
cogs                       0
gross margin percentage    0
gross income               0
Rating                     0
dtype: int64
Cantidad de nulos en la columna Date:
0
Fecha convertida:
Date    datetime64[us]
dtype: object
Cantidad convertida:
Quantity    int64
dtype: object
Filas duplicadas: 0
Columna payment duplicada: 997

**Transformacion de datos**

1.Crear nuevas columnas, ya que el dataset seleccionado viene con bastante informacion se decide realizar una comprobacion del valor neto para verificar si los montos son correctos y con esto podriamos tambien calcular un promedio por unidad.

2.Normalizar, se realiza la normalizacion del total para escalar los valores en un rango especifico.

3.Clasificar datos, se decide realizar una clasificacion de las ventas, si el total es mayor a 500 se considera venta alta, si el valor es menor se considera venta baja.

In [3]:
#Comprobacion valor neto
df['Comprobacion_valor_neto'] = df['Unit price'] * df['Quantity']
print("Nueva Columna:")
df[['cogs', 'Comprobacion_valor_neto']].head()

Nueva Columna:

     cogs  Comprobacion_valor_neto
0  522.83                   522.83
1   76.40                    76.40
2  324.31                   324.31
3  465.76                   465.76
4  604.17                   604.17

In [4]:
#Venta promedio por unidad
df['promedio_unidad'] = df['cogs'] / df['Quantity']
print('Promedio por unidad:')
df[['Comprobacion_valor_neto', 'promedio_unidad']].head()

   Comprobacion_valor_neto  promedio_unidad
0                   522.83            74.69
1                    76.40            15.28
2                   324.31            46.33
3                   465.76            58.22
4                   604.17            86.31

In [5]:
#normalizar columna total
max_value = df['Total'].max()
min_value = df['Total'].min()
df['Total_normalizado'] = df['Total'].apply(lambda x: (x - min_value)/(max_value - min_value))
print("Nueva columna 'Total_normalizado':")
df[['Total', 'Total_normalizado']].head()

Nueva columna 'Total_normalizado':

      Total  Total_normalizado
0  548.9715           0.521616
1   80.2200           0.067387
2  340.5255           0.319628
3  489.0480           0.463549
4  634.3785           0.604377

In [8]:
#Clasificar datos
df['Clasificacion'] = df['Total'].apply(lambda x: 'Alta' if x >= 500 else 'Baja')
print('Clasificacion:')
df[['Total', 'Clasificacion']].head()

Clasificacion:

      Total Clasificacion
0  548.9715          Alta
1   80.2200          Baja
2  340.5255          Baja
3  489.0480          Baja
4  634.3785          Alta

**Analisis de datos**

1.Primero realizaremos agrupaciones de datos con groupby donde podremos ver total de ventas por linea de producto, total de ventas por sucursal y cantidad de ventas por sucursal.

2.En este punto utilizaremos la funcion de agregacion y podremos ver un detalle por sucursal de la suma de sus ventas, un promedio y la cantidad  de ventas.

3.En este ultimo punto utilizaremos la funcion apply, continuando con la informacion de las sucursales ahora calcularemos el porcentaje de ventas por sucursal.

In [10]:
#Agrupaciones con Groupby
ventas_por_linea_producto = df.groupby('Product line')['Total'].sum()
print("Ventas por linea de producto:")
print(ventas_por_linea_producto)


ventas_por_tienda = df.groupby('Branch')['Total'].sum()
print("Ventas por tienda:")
print(ventas_por_tienda)

grouped = df.groupby('Branch')
cantidad_ventas_branch = grouped['Total'].count()
print('Cantidad de ventas por sucursal')
print(cantidad_ventas_branch)

Ventas por linea de producto:
Product line
Electronic accessories    54337.5315
Fashion accessories       54305.8950
Food and beverages        56144.8440
Health and beauty         49193.7390
Home and lifestyle        53861.9130
Sports and travel         55122.8265
Name: Total, dtype: float64
Ventas por tienda:
Branch
A    106200.3705
B    106197.6720
C    110568.7065
Name: Total, dtype: float64

In [ ]:
#Funcion de agregacion
agregacion_branch = df.groupby('Branch')['Total'].agg(['sum', 'mean', 'count'])
print("Resumen por sucursal:")
print(agregacion_branch)

Branch
A    340
B    332
C    328
Name: Total, dtype: int64
                sum        mean  count
Branch
A       106200.3705  312.354031    340
B       106197.6720  319.872506    332
C       110568.7065  337.099715    328

In [ ]:
#Utilizacion metodo apply
total_global = df['Total'].sum()

porcentaje_branch = ventas_por_tienda.apply(lambda x: (x / total_global) * 100)
print('Porcentaje de ventas por sucursal:')
print(porcentaje_branch)